print("=== program perkenalan diri ===")
nama = input("masukkan nama kamu ")
umur = input ("masukkan umur kamu ")
print(f"halo {nama}!  umur kamu {umur} tahun ya..")
print("senang bisa berkenalan dengan kamu hobi kamu apa dan cita-cita ")
hobi = input("masukkan hobi ")
cita2 = input("masukkan cita ")
print("wah sangat menarik ")
print(f"jadi kamu {nama}, dan kamu berumur {umur}, kamu juga memiliki hobi {hobi}, dan cita-cita {cita2}")